title: Pavel's Blog
email: pavel@raiskup.cz
description: >
  FLOSS, right?

# TODO: could /blog/ work too?
blog: /blog.html

github_username: praiskup

permalink: /blog/:title.html

disqus:
  shortname: praiskup-blog

# Build settings
markdown: kramdown

theme: minima

plugins:
  - jemoji
